spring:
  application:
    name: WLED Usage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  web:
    resources:
      add-mappings: true
server:
  forward-headers-strategy: framework

github:
  releases:
    token: ${GITHUB_TOKEN:}
  oauth:
    client-id: ${GITHUB_OAUTH_CLIENT_ID:}
    client-secret: ${GITHUB_OAUTH_CLIENT_SECRET:}
