spring:
  application:
    name: WLED Usage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID:}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET:}
            scope: read:user

github:
  releases:
    token: ${GITHUB_TOKEN:}