package com.github.wled.usage.dto


data class UpgradeEventRequest(
    val deviceId: String,
    val version: String,
    val previousVersion: String,
    val releaseName: String,
    val chip: String,
    val ledCount: Int,
    val isMatrix: Boolean,
    val bootloaderSHA256: String,
    val brand: String? = null,
    val product: String? = null,
    val flashSize: Int? = null,
    val partitionSizes: String? = null,
    val psramSize: Int? = null,
    val psramPresent: Boolean? = null,
    val repo: String? = null,
    // Filesystem
    val fsUsed: Int? = null,
    val fsTotal: Int? = null,
    // Bus / hardware
    val busCount: Int? = null,
    val busTypes: List<String>? = null,
    // Feature flags
    val hasRGBW: Boolean? = null,
    val hasCCT: Boolean? = null,
    val ablEnabled: Boolean? = null,
    val cctFromRgb: Boolean? = null,
    val whiteBalanceCorrection: Boolean? = null,
    val gammaCorrection: Boolean? = null,
    val autoSegments: Boolean? = null,
    val nightlightEnabled: Boolean? = null,
    val relayConfigured: Boolean? = null,
    val buttonCount: Int? = null,
    val i2cConfigured: Boolean? = null,
    val spiConfigured: Boolean? = null,
    val ethernetEnabled: Boolean? = null,
    val hueEnabled: Boolean? = null,
    val mqttEnabled: Boolean? = null,
    val alexaEnabled: Boolean? = null,
    val wledSyncSend: Boolean? = null,
    val espNowEnabled: Boolean? = null,
    val espNowSync: Boolean? = null,
    val espNowRemoteCount: Int? = null,
    // Usermods
    val usermods: List<String>? = null,
    val usermodIds: List<Int>? = null,
)
